# To get started , we import the nacessary tools . 

In [1]:
import numpy as np # for numerical computations 
import pandas as pd  # for data cleaning and manipulation 
import matplotlib.pyplot as plt # for basic plotting 
import seaborn as sns # for enhaced statistical visualization 
%matplotlib inline  
# -> this line ensures that matplotlib plots appear inline in the notebook 

we want to load dataset and name it (Df) 

In [2]:
df=sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

# the frist step : is to analyze each column one by one and define what each represents
-survived ----> indicates whether the passengers on board the Titanic are alive or dead, with 0 indicating death and 1 indicating life.


-pclass ----> There are three cabins or three floors on this ship, which are floors 1, 2, and 3, respectively, and this column indicates the location of passengers in different classes.


-sex ----> the sex column represents the gender of the passengers on the Titanic.


-age ----> The Age column represents the age of the Titanic passengers.


-sibsp ---->  The sibsp column shows how many siblings or spouses each passenger had on board.


-parch ----> The parch shows how many parents or children each passenger had with them on the ship.


-fare ---->  The fare column indicates the price of each ticket that the passenger paid to board this ship.


-embarked ----> The embarked column in the Titanic dataset indicates which port the passenger boarded the Titanic from.
C=Cherbourg------S=Southampton------Q=Queenstown



-class ----> There are three cabins or three floors on this ship, which are floors 1, 2, and 3, respectively, and this column indicates the location of passengers in different classes.(But in this column it is not written as a number, but as a string)


-who ----> The who column shows the same gender as man and women.


-adult_male ---->  The adult male column in the Titanic dataset is a Boolean column that indicates whether the passenger was an adult male or not . True = male and age>=18 ------ false= female and age<18 .


-deck ----> The deck column in the Titanic dataset indicates which deck or upper floor of the ship the passenger stayed on.


-embark_town ----> The embarked column in the Titanic dataset indicates which port the passenger boarded the Titanic from.


-alive ----> The alive column represents a string indicating whether the passengers survived or not.


-alone ----> The "alone" sign indicates whether or not the passengers are alone.



# Now that we have the concept of all the columns, we move on to the second step of cleaning the dataset:

In [ ]:
# Checking whether there are missing values ​​in the existing dataset:
df.isna().any()
 # # # according to this command, we found that there are missing values ​​in the (age) column, the (deck) column, and the (embarked) and (embark town) columns

survived       False
pclass         False
sex            False
age             True
sibsp          False
parch          False
fare           False
embarked        True
class          False
who            False
adult_male     False
deck            True
embark_town     True
alive          False
alone          False
dtype: bool

In [ ]:
# Now I want to find the percentage of missing values ​​in each column:
(df.isna().sum() / len(df) *100).round(2).sort_values(ascending=False)
# # # 
# According to this command, we understood that the highest missing value in the form of Nan shown in the deck column is 77%, and after that in the age and ebmraked columns, it is 19% and 0.22%, respectively.


deck           77.22
age            19.87
embarked        0.22
embark_town     0.22
sex             0.00
pclass          0.00
survived        0.00
fare            0.00
parch           0.00
sibsp           0.00
class           0.00
adult_male      0.00
who             0.00
alive           0.00
alone           0.00
dtype: float64

In [ ]:
#Now we consider the number of missing values ​​in each column:
df.isna().sum().sort_values(ascending=False)
# # #

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

# Before we examine the missing values ​​in each column, we check whether each column has outliers or not by taking a unique value from each column:

In [ ]:
# survived column : # 1
df['survived'].unique() 
### there is no outlier 


array([0, 1])

In [ ]:
# pclass column : # 2
df['pclass'].unique()
### there is no outlier 

array([3, 1, 2])

In [ ]:
# sex column : # 3 
df['sex'].unique()
### there is no outlier 

array(['male', 'female'], dtype=object)

In [ ]:
# age column : # 4 
df['age'].unique() 
### there is an outlier             (******)
# With this command, we found ages that are less than one year old, which doesn't make sense

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [ ]:
# sibsp column : # 5 
df['sibsp'].unique() 
### there is no outlier  I'm not too sure :/ 

array([1, 0, 3, 4, 2, 5, 8])

In [ ]:
# parch column : #6 
df['parch'].unique()
### there is no outlier 

array([0, 1, 2, 5, 3, 4, 6])

In [ ]:
# fare columnc: #7 
df['fare'].unique()
### Needs further investigation               (******)

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [ ]:
# embarked column : #8 
df['embarked'].unique()
# there is an outlier ----> (nan)     (******)

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
# class column : #9 
df['class'].unique() 
# there is no outlier 

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [ ]:
# who column : #10 
df['who'].unique() 
# there is no outlier 

array(['man', 'woman', 'child'], dtype=object)

In [ ]:
# adult_male column : #11 
df['adult_male'].unique()
# there is not outlier 

array([ True, False])

In [ ]:
# deck column : #12 
df['deck'].unique() 
# there is no outlier 

[NaN, 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [29]:
# alive column : #13 
df['alive'].unique()
# ther is no outlier 

array(['no', 'yes'], dtype=object)

In [ ]:
# alone column : #14 
df['alone'].unique()
# there is no outlier 


array([False,  True])

Conclusion: According to the above commands, the columns that need to be checked for outliers are as follows: 
1. (Embraked column ) 
2. (fare column )
3. (sibsp column)
4. (age column )

# After analyzing and reviewing the columns of the existing dataset with the conclusions we had, we begin cleaning them logically and with reason and argument : 