# To get started , we import the nacessary tools . 

In [1]:
import numpy as np # for numerical computations 
import pandas as pd  # for data cleaning and manipulation 
import matplotlib.pyplot as plt # for basic plotting 
import seaborn as sns # for enhaced statistical visualization 
%matplotlib inline  
# -> this line ensures that matplotlib plots appear inline in the notebook 

we want to load dataset and name it (Df) 

In [2]:
df=sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

# the frist step : is to analyze each column one by one and define what each represents
-survived ----> indicates whether the passengers on board the Titanic are alive or dead, with 0 indicating death and 1 indicating life.


-pclass ----> There are three cabins or three floors on this ship, which are floors 1, 2, and 3, respectively, and this column indicates the location of passengers in different classes.


-sex ----> the sex column represents the gender of the passengers on the Titanic.


-age ----> The Age column represents the age of the Titanic passengers.


-sibsp ---->  The sibsp column shows how many siblings or spouses each passenger had on board.


-parch ----> The parch shows how many parents or children each passenger had with them on the ship.


-fare ---->  The fare column indicates the price of each ticket that the passenger paid to board this ship.


-embarked ----> The embarked column in the Titanic dataset indicates which port the passenger boarded the Titanic from.
C=Cherbourg------S=Southampton------Q=Queenstown



-class ----> There are three cabins or three floors on this ship, which are floors 1, 2, and 3, respectively, and this column indicates the location of passengers in different classes.(But in this column it is not written as a number, but as a string)


-who ----> The who column shows the same gender as man and women.


-adult_male ---->  The adult male column in the Titanic dataset is a Boolean column that indicates whether the passenger was an adult male or not . True = male and age>=18 ------ false= female and age<18 .


-deck ----> The deck column in the Titanic dataset indicates which deck or upper floor of the ship the passenger stayed on.


-embark_town ----> The embarked column in the Titanic dataset indicates which port the passenger boarded the Titanic from.


-alive ----> The alive column represents a string indicating whether the passengers survived or not.


-alone ----> The "alone" sign indicates whether or not the passengers are alone.



# Now that we have the concept of all the columns, we move on to the second step of cleaning the dataset:

In [3]:
# Checking whether there are missing values ​​in the existing dataset:
df.isna().any()
 # # # according to this command, we found that there are missing values ​​in the (age) column, the (deck) column, and the (embarked) and (embark town) columns

survived       False
pclass         False
sex            False
age             True
sibsp          False
parch          False
fare           False
embarked        True
class          False
who            False
adult_male     False
deck            True
embark_town     True
alive          False
alone          False
dtype: bool

In [4]:
# Now I want to find the percentage of missing values ​​in each column:
(df.isna().sum() / len(df) *100).round(2).sort_values(ascending=False)
# # # 
# According to this command, we understood that the highest missing value in the form of Nan shown in the deck column is 77%, and after that in the age and ebmraked columns, it is 19% and 0.22%, respectively.


deck           77.22
age            19.87
embarked        0.22
embark_town     0.22
sex             0.00
pclass          0.00
survived        0.00
fare            0.00
parch           0.00
sibsp           0.00
class           0.00
adult_male      0.00
who             0.00
alive           0.00
alone           0.00
dtype: float64

In [5]:
#Now we consider the number of missing values ​​in each column:
df.isna().sum().sort_values(ascending=False)
# # #

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

# Before we examine the missing values ​​in each column, we check whether each column has outliers or not by taking a unique value from each column:

In [6]:
# survived column : # 1
df['survived'].unique() 
### there is no outlier 


array([0, 1])

In [7]:
# pclass column : # 2
df['pclass'].unique()
### there is no outlier 

array([3, 1, 2])

In [8]:
# sex column : # 3 
df['sex'].unique()
### there is no outlier 

array(['male', 'female'], dtype=object)

In [9]:
# age column : # 4 
df['age'].unique() 
### there is an outlier             (******)
# With this command, we found ages that are less than one year old, which doesn't make sense

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [10]:
# sibsp column : # 5 
df['sibsp'].unique() 
### there is no outlier  I'm not too sure :/ 

array([1, 0, 3, 4, 2, 5, 8])

In [11]:
# parch column : #6 
df['parch'].unique()
### there is no outlier 

array([0, 1, 2, 5, 3, 4, 6])

In [12]:
# fare columnc: #7 
df['fare'].unique()
### Needs further investigation               (******)

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [13]:
# embarked column : #8 
df['embarked'].unique()
# there is an outlier ----> (nan)     (******)

array(['S', 'C', 'Q', nan], dtype=object)

In [14]:
# class column : #9 
df['class'].unique() 
# there is no outlier 

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [15]:
# who column : #10 
df['who'].unique() 
# there is no outlier 

array(['man', 'woman', 'child'], dtype=object)

In [16]:
# adult_male column : #11 
df['adult_male'].unique()
# there is not outlier 

array([ True, False])

In [17]:
# deck column : #12 
df['deck'].unique() 
# there is no outlier 

[NaN, 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [18]:
# alive column : #13 
df['alive'].unique()
# ther is no outlier 

array(['no', 'yes'], dtype=object)

In [19]:
# alone column : #14 
df['alone'].unique()
# there is no outlier 


array([False,  True])

Conclusion: According to the above commands, the columns that need to be checked for outliers are as follows: 
1. (Embraked column ) 
2. (fare column )
3. (sibsp column) ^
4. (age column ) ^

# After analyzing and reviewing the columns of the existing dataset with the conclusions we had, we begin cleaning them logically and with reason and argument : 

In [20]:
#review and clening column 'deck'
df.drop(columns='deck',inplace=True)
#the 'deck' column was removed because it contained around 77% missing values , making it unrelilaable . 

In [21]:
# review and claning column 'age'
df['age']=df['age'].fillna(df['age'].median())
###

the missing value in the 'age' column were imputed using the median ,as it is less affected by extreme values .
how ever some invalid enttries (such as perecentages or non-numeric data ) were detected in this column . 
these values will be reviewed and either corrected or removed to maintain data quality and consistency .

In [22]:
# review column 'age' 
df[df['age']<1]

survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
78          1       2    male  0.83      0      2   29.0000        S  Second   
305         1       1    male  0.92      1      2  151.5500        S   First   
469         1       3  female  0.75      2      1   19.2583        C   Third   
644         1       3  female  0.75      2      1   19.2583        C   Third   
755         1       2    male  0.67      1      1   14.5000        S  Second   
803         1       3    male  0.42      0      1    8.5167        C   Third   
831         1       2    male  0.83      1      1   18.7500        S  Second   

       who  adult_male  embark_town alive  alone  
78   child       False  Southampton   yes  False  
305  child       False  Southampton   yes  False  
469  child       False    Cherbourg   yes  False  
644  child       False    Cherbourg   yes  False  
755  child       False  Southampton   yes  False  
803  child       False    Cherbourg   yes  False  
831  child       False  Southampton   yes  False

In [23]:
df['age'].dtype

dtype('float64')

some 'age' values were recorded as decimals (e.g,0.85,0.92,0.75 and...) representing infants ypunger than one year old .
these values  are valid and were kept in the dataset as the provide accurate information about passenger ages . 

In [24]:
df['age'].describe()

count    891.000000
mean      29.361582
std       13.019697
min        0.420000
25%       22.000000
50%       28.000000
75%       35.000000
max       80.000000
Name: age, dtype: float64

In [35]:
#cheking outlier 
Q1 = df['age'].quantile(0.25)
Q2 = df['age'].quantile(0.75)
IQR=Q2-Q1
lower_bound =Q1-1.5*IQR
upper_bound=Q2+1.5*IQR
outliers_column_age=df[(df['age']<lower_bound) | (df['age']>upper_bound)]


the interquartile range (IQR) method identifies outliers by measuring the sparead of the middle 50% of data . values below Q1-1.5*IQR or above Q2+1.5*IQR are considered potential outliers. 

In [ ]:
# review column 'sibsp'  
df['sibsp'].unique() 


array([1, 0, 3, 4, 2, 5, 8])

In [38]:
Q1sibsp=df['sibsp'].quantile(0.25)
Q2sibsp=df['sibsp'].quantile(0.75)
IQRsibsp=Q2sibsp-Q1sibsp
lower_bound2=Q1sibsp-1.5*IQRsibsp
upper_bound2=Q2sibsp+1.5*IQRsibsp
outliers_column_sibsp=df[(df['sibsp']<lower_bound2) | (df['sibsp']>upper_bound2)]




doubt cleared about column 'sibsp'

In [41]:
# review column 'fare'  
df['fare'].min()

np.float64(0.0)

In [42]:
df[df['fare']<0]

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, embark_town, alive, alone]
Index: []

In [43]:
df[df['fare']==0]

survived  pclass   sex   age  sibsp  parch  fare embarked   class  who  \
179         0       3  male  36.0      0      0   0.0        S   Third  man   
263         0       1  male  40.0      0      0   0.0        S   First  man   
271         1       3  male  25.0      0      0   0.0        S   Third  man   
277         0       2  male  28.0      0      0   0.0        S  Second  man   
302         0       3  male  19.0      0      0   0.0        S   Third  man   
413         0       2  male  28.0      0      0   0.0        S  Second  man   
466         0       2  male  28.0      0      0   0.0        S  Second  man   
481         0       2  male  28.0      0      0   0.0        S  Second  man   
597         0       3  male  49.0      0      0   0.0        S   Third  man   
633         0       1  male  28.0      0      0   0.0        S   First  man   
674         0       2  male  28.0      0      0   0.0        S  Second  man   
732         0       2  male  28.0      0      0   0.0        S  Second  man   
806         0       1  male  39.0      0      0   0.0        S   First  man   
815         0       1  male  28.0      0      0   0.0        S   First  man   
822         0       1  male  38.0      0      0   0.0        S   First  man   

     adult_male  embark_town alive  alone  
179        True  Southampton    no   True  
263        True  Southampton    no   True  
271        True  Southampton   yes   True  
277        True  Southampton    no   True  
302        True  Southampton    no   True  
413        True  Southampton    no   True  
466        True  Southampton    no   True  
481        True  Southampton    no   True  
597        True  Southampton    no   True  
633        True  Southampton    no   True  
674        True  Southampton    no   True  
732        True  Southampton    no   True  
806        True  Southampton    no   True  
815        True  Southampton    no   True  
822        True  Southampton    no   True

some passengers have a fare value of 0 , which is not an error . this usually occurs because certain individuals(such as crew members,children , or family members on a group ticket) did not separately . therefore ,these values are not considered outliers and will be kept in the datset . 

doubt cleared about column 'sibsp'

In [45]:
## review column 'embark_town' and 'embarked'
df['embark_town'].isna().sum()
  

np.int64(2)

In [ ]:
df['embarked'].isna().sum()

np.int64(2)

In [47]:
df['embark_town'].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [48]:
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
df.groupby(['embarked','embark_town']).size()
# so we conclude that these two columns have equal values . 

embarked  embark_town
C         Cherbourg      168
Q         Queenstown      77
S         Southampton    644
dtype: int64

In [52]:
df.drop(columns=['embarked'],inplace=True)

# the columns 'emnarked' and 'embark_town' contain same information , wit 'embarked' being a short -coded version of the ull town name. since they are redundant and this project does not involve model building , the encoded column ('embarked') was removed , and the more descriptive 'embark_town' column was kept. 

In [ ]:
df['embark_town'].isna().sum()

np.int64(2)

In [ ]:
df['embark_town'].fillna('Southampton',inplace=True)


In [56]:
df['embark_town'].isna().sum()

np.int64(0)

the missing value in the 'embark_town' column were filled with 'southampton' ,since the majority of passengers embarked from southampton . this is a reasonable and commonly used approach because it preserves the overall distribution of the feature . 

In [57]:
df.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

# data cleaned 

In [59]:
df.corr(numeric_only=True)

survived    pclass       age     sibsp     parch      fare  \
survived    1.000000 -0.338481 -0.064910 -0.035322  0.081629  0.257307   
pclass     -0.338481  1.000000 -0.339898  0.083081  0.018443 -0.549500   
age        -0.064910 -0.339898  1.000000 -0.233296 -0.172482  0.096688   
sibsp      -0.035322  0.083081 -0.233296  1.000000  0.414838  0.159651   
parch       0.081629  0.018443 -0.172482  0.414838  1.000000  0.216225   
fare        0.257307 -0.549500  0.096688  0.159651  0.216225  1.000000   
adult_male -0.557080  0.094035  0.247704 -0.253586 -0.349943 -0.182024   
alone      -0.203367  0.135207  0.171647 -0.584471 -0.583398 -0.271832   

            adult_male     alone  
survived     -0.557080 -0.203367  
pclass        0.094035  0.135207  
age           0.247704  0.171647  
sibsp        -0.253586 -0.584471  
parch        -0.349943 -0.583398  
fare         -0.182024 -0.271832  
adult_male    1.000000  0.404744  
alone         0.404744  1.000000

# remove duplicate or equvivalent columns 
survived <--> alive


pclass <--> class


since we are not building a model , we remove 'survived' and 'pclass' as well. 

In [ ]:
df.drop(columns=['pclass','survived'],inplace=True)

In [63]:
df

sex   age  sibsp  parch     fare   class    who  adult_male  \
0      male  22.0      1      0   7.2500   Third    man        True   
1    female  38.0      1      0  71.2833   First  woman       False   
2    female  26.0      0      0   7.9250   Third  woman       False   
3    female  35.0      1      0  53.1000   First  woman       False   
4      male  35.0      0      0   8.0500   Third    man        True   
..      ...   ...    ...    ...      ...     ...    ...         ...   
886    male  27.0      0      0  13.0000  Second    man        True   
887  female  19.0      0      0  30.0000   First  woman       False   
888  female  28.0      1      2  23.4500   Third  woman       False   
889    male  26.0      0      0  30.0000   First    man        True   
890    male  32.0      0      0   7.7500   Third    man        True   

     embark_town alive  alone  
0    Southampton    no  False  
1      Cherbourg   yes  False  
2    Southampton   yes   True  
3    Southampton   yes  False  
4    Southampton    no   True  
..           ...   ...    ...  
886  Southampton    no   True  
887  Southampton   yes   True  
888  Southampton    no  False  
889    Cherbourg   yes   True  
890   Queenstown    no   True  

[891 rows x 11 columns]

# i want to create some new feature that will make analysis easier . 

In [66]:
df['family_size']=df['sibsp']+df['parch'] + 1 


In [76]:
df['age_group']=pd.cut(df['age'],bins=[0,12,18,40,60,120],labels=['child','teen','adult','middle_age','senior'])



Two new features were created to enhance the dataset:

1. Family Size: The 'family_size' column was created by summing the number of siblings/spouses ('sibsp') and parents/children ('parch') for each passenger, and adding 1 to include the passenger themselves. This feature represents the total number of family members on board.

2. Age Group: The 'age_group' column was created by categorizing passengers' ages into bins such as 'child', 'teen', 'adult', 'middle_age', and 'senior'. This allows for easier analysis of patterns based on age categories rather than exact ages.

In [77]:
df


sex   age  sibsp  parch     fare   class    who  adult_male  \
0      male  22.0      1      0   7.2500   Third    man        True   
1    female  38.0      1      0  71.2833   First  woman       False   
2    female  26.0      0      0   7.9250   Third  woman       False   
3    female  35.0      1      0  53.1000   First  woman       False   
4      male  35.0      0      0   8.0500   Third    man        True   
..      ...   ...    ...    ...      ...     ...    ...         ...   
886    male  27.0      0      0  13.0000  Second    man        True   
887  female  19.0      0      0  30.0000   First  woman       False   
888  female  28.0      1      2  23.4500   Third  woman       False   
889    male  26.0      0      0  30.0000   First    man        True   
890    male  32.0      0      0   7.7500   Third    man        True   

     embark_town alive  alone  family_size age_group  
0    Southampton    no  False            2     adult  
1      Cherbourg   yes  False            2     adult  
2    Southampton   yes   True            1     adult  
3    Southampton   yes  False            2     adult  
4    Southampton    no   True            1     adult  
..           ...   ...    ...          ...       ...  
886  Southampton    no   True            1     adult  
887  Southampton   yes   True            1     adult  
888  Southampton    no  False            4     adult  
889    Cherbourg   yes   True            1     adult  
890   Queenstown    no   True            1     adult  

[891 rows x 13 columns]

## 1. Data Cleaning

The dataset has been cleaned and prepared for analysis. The following steps were performed:

- Duplicate and redundant columns removed: Columns such as survived, pclass, and other duplicates were removed to simplify the dataset.
- Missing values handled: Missing values in columns like Age and Embarked were filled using median imputation or the most frequent value.
- Outliers managed: Outliers in numerical columns such as Age and Fare were detected and removed to ensure reliable analysis.

## 2. Feature Engineering

Two new features were created to enhance the dataset:

1. Family Size: The family_size column was created by summing sibsp and parch and adding 1 to include the passenger themselves. This feature represents the total number of family members on board.
2. Age Group: The age_group column was created by categorizing passengers' ages into bins: child, teen, adult, middle_age, and senior. This allows for easier analysis of patterns based on age categories rather than exact ages.

These steps ensured the dataset is clean, consistent, and enriched for exploratory analysis